<a href="https://colab.research.google.com/github/pran-pixel/NASSCOM1/blob/main/Loading_Datasets_from_Multiple_Sources.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
!pip install kaggle kagglehub

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

In [11]:
from google.colab import files
files.upload()

Saving 25wh1a05x7.png to 25wh1a05x7.png

{'25wh1a05x7.png': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x02C\x00\x00\x01m\x08\x06\x00\x00\x00\x04wn@\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00\x19tEXtSoftware\x00gnome-screenshot\xef\x03\xbf>\x00\x00\x00-tEXtCreation Time\x00Wed 04 Feb 2026 11:02:25 AM IST\xdc\xb4~a\x00\x00 \x00IDATx\x9c\xec\xddy@TU\xdf\xc0\xf1\xef\xbd3,\x8a\xca"*\xe5n\xa5\xa6\xf9dY\x8f\x8a\x99f\x99i\xfa\xb8d>e{n\x94\x99IYi.\xbdZ\x9aYf\x1a\x99[>efj\xee\xe5\x1a\x9a\x9a\x02n\xa8\xa9a$(\x82\x82\xc82"*0s\xef\xfb\xc7\x00\x0e\x9b\xce\xc0\x00"\xbf\xcf\xf3\xcc\xf3\xe0\xcc\xe1\x9c{\xee=s\xef\x8fs\xce\xbdGy\xb4}}\x1dA\xd2a\xb7\xf2\xde\x04!\x84\x10B\x94\x03\xb5\xbc7@\x08!\x84\x10\xa2<I0$\x84\x10B\x88JM\x82!!\x84\x10BTj\x12\x0c\t!\x84\x10\xa2R\x93`H\x08!\x84\x10\x95\x9a\x04CB\x08!\x84\xa8\xd4$\x18\x12B\x08!D\xa5&\xc1\x90(?\x8a\'\x0f\x8e\x9a\xca\xf8\xc1\xcd1\x94\xf7\xb6\x14\xc9H\xdd\xa7\xa7\xb3\xf6\xfcZ\x86\xb4(|+]\x1bwe\xc4\x8a\xf5lM8\xca\x9e\xe8\r\x04M\xedI\xa3\xaa\xa5\x9fN\x08!\x84sH0$\xca\x8fR\x83\xe6O\xf6\xc2\xffnO\x94\xf2\xde\x96\xc2\xb8\xd5\xe5\xa1\t\x0b\xf9v\xde\x7f\xa8\xefZx\x12\xc5\xb3\x03\x81\xabg\xd2\xcfk\x0f\xb3\x07\xbeJ\xe0\xd8m\xb8<\xf3)A3\x1e\xc5[)\xbdtB\x08!\x9c\xc7\x08E=\x80\xba\xa4g^y\xb0\xb5\xa8\xb8\x8c\xad^\xe2\xcb\x15o\xd1\xf4\xdc\xaf\xcc\x7f7\x86\xe7>\xf9W!\xa9\x0c4xy$}j\xff\xc1\x94\'>a]\xbc\x0e\xec\xe3DV}V\xce\x1b\xc9\xd3\xb3\x7fg\xde1K)\xa4\x13B\x08\xe1L\xaaBQ\xff\xe1\x86\xaf[\x8f\x1b\x8d;w\xe6.\x9f\x1b\r\xda8;\x9d\x03\x14_\x1e\x9d\xb9\x92uQ\xe1\x84\x99"\xd8\x97\x10\xc2\xca\xf5\x13\xe9\xdd\xca#\xf7\x98(u\xba\x10\xb8i\x0b\xc1\t\xc7\x08=\xb3\x99\xa0O\x862t\xe1\xcfl<w\x88\xcd\xdb&\xd3\xe3.\xdbn\x0e\x035;\xbc\xc8\xf8\r\x9b\xf9-\xe1O\xfe\x88\xde\xcc\xdc\xaf^\xa2M\x1d\xdbmv\xa5\xe3\xdc\xfd\x84\xad\xee\x8f\x97\xcd\x81W\xeb\xbd\xc0\xfc\xa4=\x8c\xeb\xe2\x92\x9bW\xfd\x01\x13\x99\x15\xbc\x91\x8d\xb1G\xd8k:\xce\x9e\xd3[Y\xb4\xe8u:\xd47\xda\xe4\xe7\x82\x7fP\x18\x07\xd2\xb6\x11\xd8\xde\r\xbf\x80\x1f\xd8\x97\x1eIxz$\xe1\xe9\xc7\x08z\xc9\xa7\xdc\xdb\x97\xf9\xe4N\xe6\xbf\xdc\x83\x9e\x8f\x8ccexZ\xe1\xa1\xbd\xea\x87\x7f\x8f\x96h\xbb6\xf0{BN\n\x9d\x94M\x1b\xd9\x9bq\'\x1d\xbb5\xb0v\xbd:;\x9d\x10B\x08\xa72jW4Pl\x83\x9b\x9c\x9f\xf2\x9f\xfe\xad\xef+J\xfew\xf2\xff#\xffe,;s\x9d|\xe5\x94\x8c^dyE\xbbaJC=\x1e\x18\xfe!\x81\x9d\x14\x8e\xaf^\xc6\xf2y+\xd8~ \x91\xcc\xd2N\xe7\x08\xdd\xc4\x89\xe5\xb3\x99\xb48\x9e\xa4\x8b\x19\xa8^M\xe8\x188\x9e\xb1+\x8c\x9c\x7f`<!\x97@\xf1\xbc\x8b\xfb\x1fte\xf7k}Yp\xb2-\x81\xab>\xe0\xbf\x07\xa63\xba\xdb\x11ZN\x98\xc5\xf89\xd1\x1c\xed\xf6-1\x16\x05\x8f\x8e\xef0g\xd5@\x94_f3m\xc0aL\xbe\xf7\xd2\xe7\xfd@\x826\xd4\xe7\xcd.\x1f\xb3\xd7\xe4H\x0f\x9f\x82o\x9bGhW;\x9c\x19\xc3&s\xe2B\x06n\r\x1e\xe4\xa9qo\xf0\xf9O*/u\xfe\x8a\x13Y\x00Y\x1c\x98\xd8\x8f\xde3\xeb\xd3g\xd1BzG\x8ca\xe8\xd4\xc3\x98\xad\x15\xe4JB\xaaC\xfd\x8a\x8a\xefS\xcc<:\x89vE\x0ce\x99\x0f\xcd\xe4\xb9\xae\xf39\xe5H\xa7\xca\xe5h\x0e\x85Z\x7f,2\x9456\xe6\xce\xa6*\xf1\xdfG\x91\xaeW\xa1A\x97Gira\x17;\x8eEq\xf2\x94\x82\x7f\xcb&\x18\x89&\xd3\xd9\xe9\x1c\xa8\x86\x10B\x88\x1b3\x1a-\xd6S}\xc1\x8b\xcf\xb5wl\xc3\xa3\xa2B\xa5k)u\x9b\x9f\x8bHR\xb0\x08\x87]\xcbF/\xec\xcd\x82\xec)\xcbr\x92\x15O?\xca\x96\x16\x9d\xe95\xe8Y\x86\xad\x0b\xe0\x9d\x93\xc1\xac\x99\xbf\x84\x95+\x0f\x10\x7fY/\x9dt\x0e\xc9"v\xcf\xef\xc4\xe6\xfe;\x9a\xe8\xd1\xb7\xd3\xe1\xf0P:\xddo$d\xa79\xbb\xbeW8\x1fy\x92\x98C\xa9\xec>\xfa.\xcd\xa2\xfe\xe4\xc8\x91}D,\x0fg\xf8\x17\xcdhd\x84\x18\x1a\xd2\xef\xc3\xe7\xf1\xdb\xfd\x11\x03\x06-#^\x03\xd8\xc7\xfe\x90df\xec\x9d\xcc\xc8\xa1?\xf1\xc2\xf4\x7f\xd0\x1c\xdcB=\xe98!\x9b\xf6p\xda\x02\x84\x1d <\xf16\xd6\xac\xfe\x0f\xdd\xfe5\x87\x13\x07\xac\x11I\xc6\x858b\x93ULWu\xcc\xa6\x04\xce\x9c<\x9d\x1d\x0c9NO\xd9\xc2\x94\x8e\xe1T)\xea\xf8_M"\xae4F\x97\x8c5\xa8Q]\'-\xc9\x84\xda\xfc\x15>Y\xf5\x16\xcd\x12\x7f$\xa0\xd5\x1cL):n^\x9e\xb8+\x90\xe9\xect2\x02-\x84\x10N\xa5\xeaX\xffC\x81\xd75\xb6\xef\x14\xfc4\x7f\xca\x1b(\xbc\x08\xe7(\xac\x1a\x0e\x97e\xc1t<\x98\x1f\xde\x1e\xccSM{0f\xe1\x19\xea\x0f\x99\xc5\xaa\x88\xf5\xcc\x18\xf70\xb5\xd4\xd2Jg/w\x1a\xf4\x1c\xce\xe4\r\xbf\xb2)\xee\x08\xa1\t\xfb\xd9\xb0a\x08\xcd\\=\xf1\xf2),3\r\xcdBn\x97\x9e\xa6i\xa0\xaa\xd6\xa1\xce\x9ami\xdfZ\xe7\xe0\xb2M$\xd8D<\xda\xd9\xcdl\xd8\x9e\xc9\x9d\x8f\xfaS\xdb\t\xe32\x99\x7f\x1e%J\xab\x83\xdf\xed\xa5t\xcf\x98%\x8d\x84\xc8(N\xfd]\xc4+\xc6DV\xe9\x94\x9c\x1b\xfek\xe7\xff\xe2\xd8\xa94\x12\xc3\x8fs\xae\x90\xc0\xcb\xd9\xe9\x84\x10B8\x8fLA\xb8\x0e==\x96#[\xb7\xb3k\xf3^b]\xee\xa4\xed\xe3-\xf1.d\x8f9;]\xd1T\xfc\x06\xce`\xd1\xe2\x81\xd4>\xbc\x98i\x03_\xe4\x95\x1e\x01L\xfat\x07\xf1\x16\xc5\xe1!H\xc5\xdb\x1bO5\x9d\xa4\xf3\x97\xf3\xc5\x8b\x19\\\x887AM\x1f\xbcl\xb7O)\xde \xa7~\xf5\nWP1\xdc\xbc\xf7\xcf\x17\x8f\xf9"\xa64\x85\x1a5=!y;\x1f\xb7n\xc3\x13\x03\x96\x13\xaby\xe2\xe9\xad\x90\x99j\xe2\xaa^\n\xe9\x84\x10B8\x95\xf1\xc6I*!\xa5\nu;\xf6\xe2\xa9\xa1\x03\xe9\xdd\xbd!\xe9!\xeb\xf9yh\x1f\xd6n\x8c\xc0d.\xc5t7\xdc.\x1f\xfc\x9f\xe9\x84\xfb\xe61\x8c\x1e\xbb\x8e\x8b9\x17\xc6\xc8\xba\x0c\xf8\xb2O\xe1\xbf\xa3_%z\xeb*6\'\x9c/0\xdc\xa5\xa7\xa4b\xd2=\xa8Y\xbb*\n&\x9b\x80\xc8\r\x9f\xda\x9e\x90\x9c\x8cI\x03\xd0\xc9\xca\xcc\x04\x8fjx(\x90\xea\xb4\x0b\xb2\x86E\x03\xd5\xa0\x96h.\x99Rk\x00_\x9d\xf8\x18\x7f\xb7\xc2?7\x87\xcf`@\xa79D;\xbb\x87\xc5\x1cE\xe4\t\x8d\xee\xcd\x9b\xe0\xa1\xfcy\xedxTi\xc2\x1d\x8dtN\xad\x88\xb2\x0e\xfd9;\x9d\x10B\x08\xa7\x92`\xc8\x96\xeaK\xebA\xc3x%\xa0/\xed\xfc\x12\t[\xb2\x94\t\xedV\x13\x12\x99\x967\x90pv:\x07(\x00\xba\x86fw@r\x89\x83\xb3\'r\xb0\x90O\xf4\xa40B\x0f\xa9\x0c~\xa6;~\xcb~\xe2\\\xf6F\xa9\xb7u\xa5G\x17W\xa2\xbe\n\xcd\x1e>\xb3\x10\xfbw\x0c\xf4mM\xcb\x1a\nq\xce\x8a\x86\xb44L)\x1a\xd5\xfdj\xe1\x0e\xc5\x1e\xca\xd2\x937\xf3\x91\xff!<\x8a\xe8e\xd3\xaf&\x96\xce\x9c!-\x81\x90\x8d\xc7\x18\xf5^\x0f:\xd5Y\xc7\xfax\xeb\xac:\xafn\xdd\xf9\xb7\xfbI\x96m\x89\xb1\x1egg\xa7\x13B\x08\xe1T\x12\x0c\xe5\xa1\xe2\xd7\xd4\x97\xa8\xa0\x11L_\x1eJ\xec\xa5\xa2.\xfa\xceNg\'=\x99\xd0\xb5a\x98\xa7\xbd\xc9\xf8\xb72Y\xb6-\x8a\x94L#\x1e\x8d\x9aQS\x85\xb3\x8e\xe6g9\xc5\xca\t\x8b\xe9\xb9z,A\x8b<\x99\xf7\xfd!R\xbd[\xd1s\xf4\x1btH\xfc\x89\x91s#\xb3/\xbe\x1ag\xd7\xaef\xdf\xfb\x13\x19\xb5p\x04\x86\xafw\x13{I\xa1\xda]\xcd\xf1Q\xe1t\xb1+\x94\xce\xd1=\x11\x18\xc6\xbf\xc6{\xc3\xaf\xb06<\x05\xc5\xb71\xb5\x92\x82\xd9\xb0;\xd9\xfe\xa9^\x16\x13\xe7"L\xc5\xde\x8a\xc2\x19\xa9^\xf7v\xbc\xdc\x15\x0c\xf5\xaacT\\\xf1\xac\xd7\x80\xfa\x19\x16\xae$\xc4r\xe1\x92\x06X\x88\xf9\xdf\x97\xacyu\x1e\xa3\xbe{\x17}\xda6\xce\xfb>\xc4\xa0O\xba\x92\xf1\xf3[\xac\xc8}&\x90\xb3\xd3\t!\x84p&\t\x86li\xe7\xd94z\x14\x9b\xca:\x9d\xdd4\xe2\xbe\r\xe4\rC \xaf\r\x1e\xc7\x8c1\xbeTs5s\xd9\x94J\xd2\xd1\xbd\x9c8\xe7\xf0}_\xa4\xff\xf1\x19\x01\xbd\xcf1|\xdc\xf3\x8c^:\x02\xf7\xcbq\x1c\xfbu&\xc3\'-f\xbfM\x0f\x90\x16\xb3\x82\xf1\x03\xaa\xf1\xceG/0f\xc5\xebx\xa8Y\xa4_\x88\'v\xf7N\x8e\x9e-n\x7f\x85\x85\xd3\xf3\xc60\xa9\xd1\x87\x0cy\xf7s\x9e\xf0q!#>\x82\xe0\x89{\xd9\xe8H0T\x1a\x0c\r\x19\xb0\xec\x17\xde\xb8\xef\xdaW\xe4\xb9\xd5[x\x8eL\xf6\xbc\xde\x917\xbe\xb3n\x9fn\xda\xcd\xe7}Fq\xe9\xd37y\xeb\xa7\x17\xf1\xb8r\x86\xf0\xa5\xef\xf1\xfa\xa4-$\xdbT\xc0\xd9\xe9\x84\x10B8\x8f\xd2\xb5U}9\xc5\x02\x89\'\x8b\x98p"\x84\x10B\x88[\x9a\xdcM&\x84\x10B\x88JM\x82!!\x84\x10BTj\x12\x0c\t!\x84\x10\xa2R\x93`H\x08!\x84\x10\x95\x9a\x04CB\x08!\x84\xa8\xd4$\x18\x12B\x08!D\xa5&\xc1\x90\x10B\x08!*5\t\x86\x84\x10B\x08Q\xa9I0$\x84\x10B\x88JM\x82!\x01\x8a\'\x0f\x8e\x9a\xca\xf8\xc1\xcd1\x94\xf7\xb6\x94\x80k\xe3\xae\x8cX\xb1\x9e\xad\tG\xd9\x13\xbd\x81\xa0\xa9=iT\xb5\xb4\xf3S\xa9?r9\xfb\xd2#\t\xb7}\xa5\xfd\xc1\x98\x87]JR\x1d!\x84\x10e\xc4\xbe\xb5\xc9\x94"\xde\x97\x85<n\rJ\r\x9a?\xd9\x0b\xff\xc3k\x8a<\xd47;\xc5\xb3\x03\x81\xabg\xd2-\xf1\x07\xbe\x188\x99\xf3\xb5\x1f\xe6\xd5)\x9f\x12\xe4}\x85\xe7_\x0b&\xc5\xc1\xb6j\x7f~\nnU\xdc\xb1\x1c\x08b\xd8\xa0\xd5$\xe6,\xd3\xa6\x9b\xb9t.\xcb\x895\x14B\x08QZr\x83!\x1d\xf2\x05=J\xee\'\x8an\xfb/\x9b\xcf\x95\x9c\x7f\xeb\xd6E+\x8b,F\xc9\xf3\x93\xae\x17L\xa9+\xf97\xa0d\x91\x96\xae\xdbf\xa7\x14\xc8/\xef\xbf*j\x08 \xac\x0c4xy$}j\xff\xc1\x94\'>a]\xbc\x0e\xec\xe3DV}V\xce\x1b\xc9\xd3\xb3\x7fg\x9eC+\xbe;\x96_\x95j\xeeh\xe7O\x13\x19y\x9a4gWM\x08!D\xa93^\xd2u\xd0m\x83\x03\xfd\xda\xfff\xbf\xa9\xdb\xc4\nz\xf6\x07\xd6XC\xc9\xf7[\x8e)I\xe8\xa3;\xd2[\x95?m\x91\x85\xb9\xd1\xb8s{\x8cGv\x11\x99|\xbd\x8b\xa7\xb3\xd39@\xa9A\x8b\xe7\x06\xd1\xb7{\x1b\xee\xb9\xa7\x01u\xea\xd4\xc4\xb3\x9a\x01\xb3)\x9ae\xcf\xf6f\xc6\xce\xcc\xect\xbe<\xfa\xc5\\F\xfe\xa7\tujVA\xbd\x9aB\xcc\xdeM|?\xf63\xd6\xfd\x99\x9e\xbd\x0b\\\xf0\x0f\xfa\x83\xd9/\xfbX\xc7K\xdb\xff\xc0\xbe\x80\x9c\x82\xf2\xae\xce\x0e\n\x1e-\x9ed\xd0\xb8Wx\xa2s3j\xaa&N\xef\xf9\x95\xef&|\xc9\x86\xa3\xe9\xe5\xdbI\xa8\xfa\xe1\xdf\xa3%\xda\xae\xb1\xfc\x9e\x90\xb3%:)\x9b6\xb27c\x06\x1d\xbb5`\xc1\xb1h\xb4\xebfR\xdc\xfcT\xaayU\xc7r1\x8d\x0c\'WK\x08!D\xd90fj\xd7\xbb\x8ceG\x11\xf9\x93(\xd6\xf7\x0b\xeb\xe1qD\x89~\xbb\xc06Y\xdf+4\xc0\xd2m\xd2\xe4\xfb1O\x8f\x98\xa1\x1e\x0f\x0c\xff\x90\xc0N\n\xc7W/c\xf9\xbc\x15l?\x90Hf\xfe\xb2\x9d\x9d\xce\x11j-\xda\x07\x0c\xa6K\xf2\x02>{{\x06\xd1q\xc9\xa4]\xd1q\xaf\xe9IV\xa4\xcd\xb0\x8cn\xe2\xc4\xf2\xd9LZ\x1cO\xd2\xc5\x0cT\xaf&t\x0c\x1c\xcf\xd8\x15F\xce?0\x9e\x90K\x00Y\x1c\x98\xd8\x8f\xde3\xeb\xd3g\xd1BzG\x8ca\xe8\xd4\xc3\x98\xb3\xf7\xcc\x95\x84\xd4\xdc]\xe7~\xffk\x04\xfd:\x9cZ\xbb\xbfaf\xffqDk\x8d\xe8:v\x1c\x1f\xae\xadEf\xfb@\xb6\x9e\xb7\xffh*\xbeO1\xf3\xe8$\xda\xb9\x16\xfe\xb9\xf9\xd0L\x9e\xeb:\x9fS\xf6\xc6\x8f\xc6\xc6\xdc\xd9T%\xfe\xfb(\xd2\xf5*4\xe8\xf2(M.\xecb\xc7\xb1(N\x9eR\xf0o\xd9\x04#\xd1\xf6\xefw\x87\xf2s\xc5\xcb\xd7\x83\xb4\x98T\xfb\x83-!\x84\x107\x15cN`\x03\xa0\xe8\xb6\xa7\xf3\x82CK\xb9\xca\xb4\x1b\xa0\xf0\xc2\xf2\xf6\x0ce\xcf\x03W@\xcb;\x90\x87b\xfb\xeb\x85d\x95\xa7\x96\x96\x93\xacx\xfaQ\xb6\xb4\xe8L\xafA\xcf2l]\x00\xef\x9c\x0cf\xcd\xfc%\xac\\y\x80\xf8\xcbz\xe9\xa4s\x98\xce\xc5C\xc1l\xf9\xed\x08\xb9\xf1\xc2\xa9\xfci\xb2\x88\xdd\xf3;\xb1\xb9\xff\x8e&z\xf4\xedt8<\x94N\xf7\x1b\t\xd9i\ry2.\xc4\x11\x9b\xacb\xba\xaac6%p\xe6\xe4\xe9\xec`\xc8\x86\xa1\x11\xfd\xa7\x05\xd0\xec\xc4W\xbc8p\x0e\x91\x99\x00\x7f\xf1\xcfK\x1a\xf5\xc2?\xe7\x85\x81\r\t\x9ey\xca\xee`@O\xd9\xc2\x94\x8e\xe1T)\xaaw\xefj\x12q\x8et\xa4\x19kP\xa3\xbaNZ\x92\t\xb5\xf9+|\xb2\xea-\x9a%\xfeH@\xab9\x98Rt\xdc\xbc<qW \xd3\xde\xdd\xedH~\x86\xda\xf8\xdd\xe6B\x9d\xc7\xe6\xb1\xb9O\x12\x89Q\x7fsh\xc3\xcf\xfc\xb8p;1\xe9\x0e\xd4A\x08!D\xb91j\xda\xb5K\x98\x8eJNx\xa0\x172K\xa80\xc5\xbd\x9c\xdb?KG)\xb4\xd7\'O\x90\x93\xe72|\xed\x069\x9d\x82\xc3i\x85\x96\x9b\'/\x0b\xa6\xe3\xc1\xfc\xf0v0K&\xd4\xa3M\xff\x01\xf4\x1f2\x8bU\x1f\'\x13:\xefS\xa6N\xd9\x99=I\xd6\xd9\xe9\x9c\xcd\x9d\x06=\x071\xe4\xf5\x1e<xo}\xbc\x8c\x99\xa4&\\\xa6\xaa\xab\'I>\x8e\xddD\xa8\xd4\xf6\xa7c\x1b\x08\x1b\xbe\x94\x7fl\xbaW\xf4\xd4PB\xf6\xc3\xd8\xb6\xf7P\x85S\xd8}\xed\xb7\xa4\x91\x10\xe9\xdc\xd959A\xadv\xfe/\x8e\x9dJ\xc3\xe7\xef\xe3\x9c\xb3@\xe3\xd2\xce\xcf\x12\xcb\xca\x81\xdd\xd8\xee\xe5\x89O\xfd&\xdc\xfd\xf0\xe3\xf4\x1d3\x87\xeeO~\xc6\xd0\xde\x0b8q\xb5\x04\x95\x12B\x08Q&\x8c\xa9\x99\x06r\xe6\x00q\x83i\xd0\xe5\xa3\x90\xed\xc939\x1a@\xcd\xfeg\xde\xde,\xa5\x88\xba(J\xc1\x90\xa8za%\xa7\xc7rd\xebv\xea\xd4k@\x937\x9e\xa0\xed\xe3-\xf1\xfe\xa4`\xf0\xe2\xect%\xa7\xe27p\x06\x8b\x82\xee\xe5\x9fof3mZ\x04\xf1\x97\x8cx\xdf\xdd\x9b\xb7\xbe\xea\xe3\xf0tq\xc5\xdb\x1bO\xd5\x9d\x07\xbe\xdeMhP\xbe\x92\x8c.\xe8\xa15\xa9\xa1Bzy\x8d\x13\x99/bJShR\xd3\x13\x92\xb7\xf3q\xeb6\xd6\xf7\rM\xf1\xf4V\xc8<g\xe2\xaa#\xcd\xda\xa1\xfc\xb2\xb8\x18\x17\xc3\xc588u\xecO\x0enZ\xcb\xea\xb5\xef\xf2\xdd\xe6\xd7\x19\xf2\x9f\x15\x8c^n\xba\xe9\xbeQB\x08!\xf22\xea6\xa7j\xdd&\xa4\xb8\xf6^\xd1Jz\x0f\x96}\x17\x89BJQ\x8a\x9a\x13\x9d7J\xd2\x8a\xda\xc2\x1b\x15\xacT\xa1n\xc7^<5t \xbd\xbb7$=d=?\x0f\xed\xc3\xda\x8d\x11\x98\xcc\xa5\x98\xceY\x14\x1f\xfc\x9f\xe9\x84\xfb\xe61\x8c\x1e\xbb\x8e\x8b9\xf5\x8d\xac\xcb\x80/\xfb\x14\xf2\x0b\x1a\x16\rT\x83Z\xe8\x1e\xd3\x93\x93H\xb5\xa4\x12\x1c\xf8"_\x87\x142\xf3\xe6J\x92C\x01\x9dRk\x00_\x9d\xf8\x18\x7f\xb7\xc2?7\x87\xcf`@\xa79D\xdb;Tf\x8e"\xf2\x84F\xf7\xe6M\xf0P\xfe\xbcV\xdf*M\xb8\xa3\x91\xce\xa9\x15Q\x05\x87\xfeJ1\xbf\xcb\x07\xb7\xb0\'\xe6%\x1ejQ\x1f\x15\x13N\x9a:/\x84\x10\xa2\x94\xe4y\xcePa\x17\xc2\xd2\xbc\xe9\xbct\xf2\xce;g\xc8!\xaa/\xad\x07\r\xe3\x95\x80\xbe\xb4\xf3K$l\xc9R&\xb4[MHdZ\xde\xf90\xceNW\n\x14\x00]\xe3\xba\xf3\xe3shi\x98R4\xaa\xfb\xd5\xc2\x1d\xc8\xfft\x1c=1\x94\xdd\x87\xdcy\xa1s#\xd2\xbe\xdfDR\t\xbb:\xf4\xe4\xcd|\xe4\x7f\x08\x8f"F\xeb\xf4\xab\x89\x8e\xcd\x19\xd2\x12\x08\xd9x\x8cQ\xef\xf5\xa0S\x9du\xac\x8f\xb7\x06\xc5^\xdd\xba\xf3o\xf7\x93,\xdb\x12S`\x7f+\xb5\xda\xf3\xca\xd4\x17i\x1a\xb3\x8c\x19\x1f\xfd\xcey\xadd\xf9\xe5\xc9\xbbF\x03\xea\xf9Bjb\x8a\xf4\n\t!D\x05`\xdfC\x17+\r\x15\xbf\xa6\xbeD\x05\x8d`\xfa\xf2Pb/\x15u)sv:\'\xd3\x93\t]\x1b\x86y\xda\x9b\x8c\x7f+\x93e\xdb\xa2H\xc94\xe2\xd1\xa8\x195U8[\xe0\x17\xd29\xba\'\x02\xc3\xf8\xd7xo\xf8\x15\xd6\x86\xa7\xa0\xf86\xa6VR0\x1bv\'\xa3[N\xb3j\xc2b\x9e\\5\x8d\x85\xcbZ\xf1\xe3O\xa1\xfcs6\x1d\xdd\xcd\x13\xbf&\xf0\xd7\xe2\xed\x9cr\xa4\xeb\xc5b\xe2\\\x84\xc9y\xf5\xc5B\xcc\xff\xbed\xcd\xab\xf3\x18\xf5\xdd\xbb\xe8\xd3\xb6q\xde\xf7!\x06}\xd2\x95\x8c\x9f\xdfbE\x81g\x0c\xa9\xdc\xfe\xdf7\tx\xf6\x01\\\xb2\xea\x12\xb5rW\xbe\xe7\x10\xd9\x9f\x9f\xfbC/3\xbc}:\x07\xf7\x9d$\xf1\x92B\xf5F\xad\xe9:"\x80\x87\xaf\xfc\xc6\xf8U\xe7\xe4\x0e3!\x84\xa8\x00\x94Fw\xd4\x93?^\x01\xafs\xee\xe5\xbd\t\xf61\xdc\xc1\xa0\x1dk\xe9\xb9m \xfd\'\x1c)z\x08F\xf1\xa2\xd5\x90@^\x1b\xdc\x99\x16\r}\xa9\xe6j\xe6\xb2)\x95\xa43\x91\xac\x7fg\x18\xdf\x86\xe5\x8b^\xaa\xdc\xc1\x93S>dH\xbf{\xa9\xe7\xe3BF|\x04\xc1\x13\xdf\xe2\xc3\x1fO\xe7>O\xc7\xb3M\x7f\x86\xbe\xff,\x8f\xf8\xdfE\x9d\xea\x062L\t\xc4\x1c\\\xcd\x8c\x17f\xb1\xf7b\xf97#\xd7\xc6\x8f3\xec\xd37\xe9\xdd\xa91\x1eW\xce\x10\xbe4\x88\xe9\x93\xd6\x13}\xb9\x90\xb4\xffz\x95/W\xbeI\xd3\xd3\x0b\x19\xd5{6G\n\x99\xfd}\xe3\xfc\x14<;\x0eb\xf4\xfb\xbd\xb9\xff_\r\xa9\xe5\xe9Bf\xd2\x19\xfe\xde\xb9\x81\x1f>\x9aKp\xe4\x95\xd2\xac\xae\x10B\x08\'\x91`([\x85\t\x86\x84\x10B\x08\xe1T\xb2P\xab\x10B\x08!*5\t\x86\x84\x10B\x08Q\xa9I0$\x84\x10B\x88JM\x82!!\x84\x10BTj7\xe5\xad\xf5\xb63\xba\x1d}V\x90\xa3\xb3\xc1\x0b>fR\x08!\x84\x10\x95\xc9M\x19\x0c\xd9\x06\'\xba\x1d\xe1\x8db\x93>wA\x8e\xfcK\xd6\xeb9O\xd8\xd6\xd1u\xd0u\xdd\xfa^\xde\xc4B\x08!\x84\xa8dn\x8a`\xc8\x1a\x8f\\g\x11\x10=\x7f\x80\x93\x1d\xc4d\x075y_\xb6\t\x15r\x03+\x1d\xec_hD\x08!\x84\x10\x95E\x9e`\xa8\xa8\xf0\xc0v\xfdz\xa5\x90U\xc1t\xbd`\xca\x9c\xf7rz`\xf2\x17\x92g9UkW\x8d\xf5\xff!O\xcf\xcd\xb5dJ\x11\x1bh\xbb\x1eY\xfe\xff/l\xe1\xd9\xc22\x91a2!\x84\x10\xa2\xb22\xe6\x9d\x9f\xa3\x14\x18b\xd2\x01]Wr{^\xd0m\x86\x99\xb2\xd3*J\xcep\x93\xcd\xf0VNF\xb9\xbd:\xb6AK\xce\xcf\x05\x96\x9f\xcf\xb35y\x14\xd9\x91s\xbd@\xa6\xacW[\x13B\x08!DEc\xb4d\x82\xaekh\xba\x8e\x9egUO\x95\x9c\x80E)\xd0\x9bc\xab\xa8^\x98\xc2R\xe7\x04?\xf9{p\x84(\x1b\xaeM\x1e\xe1\x85w_\xe6\x89G[\xd1\xa0\x96;Y\x17\xa28\xbcf\x11_\xfe\xdf*\xfeN\x93\xa1S!\x84\xa8\x8c\x8c\xe6\xac\x9c\xa5$m\x83\x14\xb0\rn\xf2^"\xf2\x050Ja\x01P\xfe\xb9:\x14\x92\xa6\x90\xbc\x84(ez\xb5F4v\t\xe7\xc7Qs\x88N1R\xbbu7^\x1c\xfb1\xb3\xab\xa7\xd0?`\x1b\x12\x0f\t!D\xe5\xa3\xf8\xf9\xdd.\xa7\x7f\xc0\xefb\xd5\xf2\xde\x04Q.\x0c\xdc\xf9\xfej~\x0c\xf8\x93\xb7\x9a~\xc0\x9e\xcc\xf2\xde\x1e!\x84\x10eM\x1e\xba\x98\x87\x1b\x8d;w\xe6.\x1fC\x19\xa7\xb3\x93\xb1%\xc3\x0f\xfc\xc5\xae\xc5=\xa8\x96\xe7\x83\x1a<\xb1$\x9c\xb0_\x07R;\xf7\x88*x\xb4\xe8\xc9\x9b?\xaed\xc3\xd9\xa3\x84\xc5\xeff\xf9\xaa\xb1<y\x8fG\xde\xfe8\xc5\x97Gg\xaed]T8a\xa6\x08\xf6%\x84\xb0r\xfdDz\xb7\xca\x9f\xae\x06-\x9e\x1f\xc5\x07K~`\xe9\xe1\x9dl\x8b?\xc6\x81K\x11\x84\xc5m$\xf0aW\x9bt\xd5h\xf6\xdcXf\xee\xfe\x9d\x1d\x17"\xd8\x9f\x14\xce\xb6\xbf\xb7\xb0xn_\xea\xde\x94\xadM\'\xe3\xcaU\xf4\x8c\x0c2\xe4\xcf\x02!\x84\xa8\x94n\x8a[\xebo\x1a\x86z<0\xfcC\x02;)\x1c_\xbd\x8c\xe5\xf3V\xb0\xfd@"\x05:\x0b\x9c\x9d\xce^\xe6\x13\xec\xda\x12\xc7\xcb\xcf>\xcc}U7\xb0\xebr\xf6\xfbUZ\xd3\xd6\xdf\x8d\xa8\xb9\xfb\xb9\x90=\xea\xe9~\xffk\x04\xfd:\x9cZ\xbb\xbfaf\xffqDk\x8d\xe8:v\x1c\x1f\xae\xadEf\xfb@\xb6\x9e\xcf\x99\x08f\xe2\xc4\xf2\xd9LZ\x1cO\xd2\xc5\x0cT\xaf&t\x0c\x1c\xcf\xd8\x15F\xce?0\x9e\x90K\xd9e\xa8\xb5h\x1f0\x98.\xc9\x0b\xf8\xec\xed\x19D\xc7%\x93vE\xc7\xbd\xa6\'Y\x91Y\xb9\x9b\xe8\xd1\xed\x03f\xcdjC\xf8\x84I\x8c\xd8q\x8a\x8bf7\xaa\xdf\xd6\x80;\xaa\x9d\xce\xdd6{)\xbeO1\xf3\xe8$\xda\xb9\x16\xfe\xb9\xf9\xd0L\x9e\xeb:\x9fS\x16\xc7\xf2\xcd\xcd\xdf\xb5\x06\xf5\x1ez\x86\xd1\xaf7\xe4H\xd0x\x8ed\xdd\xf8w\x84\x10B\xdczd\x98,\xdb\xb5a2\x03\x9e-:\xd3k\xd0\xb3\xf4{\xe6\xdfT?\x19\xcc\x9a\xf9KX\xb9\xf2\x00\xf1\x97mw\x95\xb3\xd3\xd9\xc7\xd8\xf6=Vn\xee\xc5\xde~\x8f\xf1\xf1\xb6\xab\xb9\xef\xad\xda\xf4\x18\xdb\xbaug\xe6^3\x18\x1a\xf1\xfc\xa6u\x0cw\x99\xc3\x8b\x8f\xcf!2;\xfaR\xbc\xbb\xf1q\xf8\xe7\xd4\x9b\xd9\x93\x97g\x9e\xa2\xa8\xd8D\xad\xf7\x02s\x0f\x0f\xe5d\xdfG\xf8d\xa79\xbb\x1aw0h\xc7Zzn\x1bH\xff\tG(<\xfe0\xd0p\xd42\x96\x07\x1ccD\xeb\x89\xec\xbd\xe2p\xf5\xf2eW\x9d:MjQ\xa5\xa8\xa9eW\x93\x88\x8b1\xe1x\x0cc\xa4\xcd\'\x9b\x08z\xbd\x01nj\x16\xb1+\xc6\xf2\xda\xd0\xb5\xc4J0$\x84\x10\x95\xd2M9pQ\xbe,\x98\x8e\x07\xf3\xc3\xdb\x83y\xaai\x0f\xc6,<C\xfd!\xb3X\x15\xb1\x9e\x19\xe3\x1e\xa6\x96ZZ\xe9\xecc>\xf0\x0b\x9b\xff\xf1\xa1S\xbf\x07q\x07\xc0@\xa3G:P\'~\'\x7f\x1c\xb6\x06.Jm\x7f:\xb6\x81\xb0\xb9K\xf9\xc7\xa6\x1bJO\r%d?\xdc\xd5\xf6\x1e\xaa\xe4\xbe\xebN\x83\x9e\xc3\x99\xbc\xe1W6\xc5\x1d!4a?\x1b6\x0c\xa1\x99\xab\'^>\x8e6\x0f\x0bg\xd6\xff\xcc~\xf7\xa7\x99\xba\xe9S\x86<\xf3\x00~UK0I\xde\x92FBd\x14\xa7\xfe.\xe2U\xac@\x08\xc0\xcc\x9f\x9f\xbe\xc43\x0f\r$0\xf0\x07\xe2\xda\x7f\xc4\xffV<\xcf\x1dE\xf4@\t!\x84\xb8\xb5I0t\x1dzz,G\xb6ng\xd7\xe6\xbd\xc4\xba\xdcI\xdb\xc7[\xe2]\xc8\x1esv\xba\xeb2G\xf0\xeb\xe2\xa3\xd4\xe8\xd9\x8b\xb6\xd5\x00\xd5\x8f\x7fwiL\xf2\xc6\xad\x1c\xc9\xb0&Q\xbc\xbd\xf1T\xdd\xe9\xf8\xf5nB\x93\x8f\x11\x96\xf3J\xda\xc3\x84\xc7]1\xd4\xacI\r\x15@\xc5o\xe0\x0c\x16-\x1eH\xed\xc3\x8b\x996\xf0E^\xe9\x11\xc0\xa4Ow\x10o)\xf8xM{h\xff\xfc\xc4\xa8\x0e\xaf2o\xaf\x17\x8f\x7f\xfa=\xbf\x9c\xdcL\xd0\xe7\x03\xb9\xaf\x8e\x93\xe6M9Ifr\x1c\xa7\x8e\xecg\xfb\xbc\xa9\x0c\xef\xf9\x05\xa7;\x04\xf2z\x1f/\xb9\xbfQ\x08!*!\x993T\xe8s\x19\xabP\xb7c/\x9e\x1a:\x90\xde\xdd\x1b\x92\x1e\xb2\x9e\x9f\x87\xf6a\xed\xc6\x08L\xe6RLg\x17\x0b1K\x7f$\xe4\xdd\t\xf4\xefW\x9b][;\xf2\xd0\xbd\xc9\xec\xfc8<w.\x92\x9e\x9cD\xaa%\x95\xe0\xc0\x17\xf9:\xa4\x90\x19JW\x92H\xd4\x00\xc5\x07\xffg:\xe1\xbey\x0c\xa3\xc7\xae\xe3b\xce\xa8]d]\x06|\xd9\xc7\xd1\r\xcb\x95\x19\x1b\xca\xb2\xd1\xa1,\x1b\xe7\xcb\xddO\xf4\xe3\xf9\xb1\xef0\xb7{k\xc6t~\x8f\xe0\xf3\xf6\x0f\r*\xb5\x06\xf0\xd5\x89\x8f\xf1w+\xfcss\xf8\x0c\x06t\x9aCt1\xe7\x0c\xe5\xb0\x9c\x0e\xe7X\xbc\x1b\xfe\xcd\xeb\xa2\x92Z\xc4\x10\xa0\x10B\x88[U%\n\x86\xf4\xdc\xc0GQ\x14\x14UAUU\x14U\xb9\xb6\x18\xac\xeaK\xebA\xc3x%\xa0/\xed\xfc\x12\t[\xb2\x94\t\xedV\x13\x12\x99\x96w~\x8d\xb3\xd39Z\x93\xf3\x9b\xf9a\xc9\x08\xbe\x0ex\x86\xf6U\xef\xe7\xde\x0b\xbf\xb104\xe3\xda\xe7\x89\xa1\xec>\xe4\xce\x0b\x9d\x1b\x91\xf6\xfd&\x92\xae\x13\x7f(\x00\xba\x86V\x1a3\xc72.\xf0\xd7\xday\x8c\xdf\x97N\xad\xa3\xef\xd1\xfd\xe1\x89\x04\xffl\xffD"=y3\x1f\xf9\x1f\xc2\xa3\x88\xde3\xfdj"qN\x88\\\xd4\xdbZ\xd2\xcc\xcfBB\xcc\xf9\x12\x1d\x17!\x84\x10\x15\xd3-\x18\x0c\xd9\\\xd5\x15@QPU\x05\x83\xc1\x80jPA\xe1Z\xf0\x93\x9b,\xa7{H\xc5\xaf\xa9/QA#\x98\xbe<\x94\xd8KEE\x08\xceN\xe7\xa8+\x84\xcf\x9e\xcf\x81\x17\xdea\xf2Xw\xce.\x98\xce\xa1\x0c\x9b\x8f-\xa7Y5a1O\xae\x9a\xc6\xc2e\xad\xf8\xf1\xa7P\xfe9\x9b\x8e\xee\xe6\x89_\x13\xf8k\xf1vN\x99\x01=\x99\xd0\xb5a\x98\xa7\xbd\xc9\xf8\xb72Y\xb6-\x8a\x94L#\x1e\x8d\x9aQS\x85\xb3\x0eo\x97J\x9d\xfe\xa3\x19v\xf7ivm\xff\x93\x98\x84\xcbhUks\xf7\x80\x9e4\xe54\xcb"\x1d\xbc\x8f\xceb\xe2\\\x84\xc9\xe1\xad(\x9a\x81\xa6/\xbfCW\xf7\xa3\x84\xff\x19\xc7\xc5,W|\x9a\xfe\x9b\'G\r\xa6\xf5\xd9U\x8cZsA\x96\xef\x15B\x88J\xa8\xe2\xdfMf\xed\xda\xb0\xf6\xf6(\n(zv\xaf\x8f\x01\xc5\x90\xb3\xde\xda\x8d\xab\xe8s\xae\xa2\xcd\x9e\xad\xc2\xfd\xd3\xd63oH\x12_>8\x90\xc5\'\xf3w\x91\xa8x\xb6\xe9\xcf\xd0\xf7\x9f\xe5\x11\xff\xbb\xa8S\xdd@\x86)\x81\x98\x83\xab\x99\xf1\xc2,\xf6\xe6\x8c\x89)^\xb4\x1a\x12\xc8k\x83;\xd3\xa2\xa1/\xd5\\\xcd\\6\xa5\x92t&\x92\xf5\xef\x0c\xe3\xdb0\xc7\xee&\xab\xdb\xe7]F\x8fz\x94{\x9a\xdf\x86wU\x03\x96\xcb\xc9\xc4\x1d\tc\xcb\x97_\xb0\xf0\x97\x98\xe2?V\xc0)\\i\xf6\xf2x\xdex\xb5=w7\xbd\r\xef*:\x97\xceEst\xeb*\xfe7\xe5{\xf6\x9d\x93\x012!\x84\xa8\x8c*l0\xa4\x1a\xac\xc3\\\xd6%\xd4tTEEQ\x14t\xa5x\xd5\xa9\x88\xc1P\xeb\xa9\xab\xf8\xac\xc1\xd7\x0cx~=\xc9\x15\xf2(\n!\x84\x10\xe5\xaf\xe2\x0e\x93\xa9\n\x06W5\xbb\xd7\xc7\xba\x16\xda-\x1f\x0f\xa8\xde\xd4o^\x03Kfu\xee\xea\xfb&\xef?\x9b\xc0\xfc\xae\x1b$\x10\x12B\x08!J\xa0\xc2\x06C\x96,\x0b\xaa\xaa\xa2\x1a\xa84\xeb\xbd\xaau\xbb\xf2\xf6\x86\t\xf8{\\"n\xdf\x16\xe6\xf7\

In [12]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [13]:
!kaggle datasets download -d heptapod/titanic

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/heptapod/titanic
License(s): DbCL-1.0
Downloading titanic.zip to /content
100% 10.8k/10.8k [00:00<00:00, 26.5MB/s]

In [14]:
import zipfile

with zipfile.ZipFile("titanic.zip", 'r') as zip_ref:
    zip_ref.extractall("dataset")

In [15]:
import pandas as pd

df = pd.read_csv("dataset/train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [16]:
import kagglehub

path = kagglehub.dataset_download("heptapod/titanic")

print("Dataset downloaded to:", path)

Using Colab cache for faster access to the 'titanic' dataset.
Dataset downloaded to: /kaggle/input/titanic

In [17]:
df = pd.read_csv(path + "/train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [6]:
import requests
import pandas as pd

url = "https://api.exchangerate-api.com/v4/latest/USD"

response = requests.get(url)
data = response.json()

rates = data["rates"]

df = pd.DataFrame(list(rates.items()), columns=["Currency","Rate"])
df.head()

  Currency    Rate
0      USD    1.00
1      AED    3.67
2      AFN   65.70
3      ALL   81.36
4      AMD  366.15

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bank.db")

data = {
    "Customer_ID":[1,2,3,4],
    "Loan_Amount":[200000,150000,300000,180000],
    "Credit_Score":[720,680,650,700]
}

df = pd.DataFrame(data)

df.to_sql("customers", conn, if_exists="replace", index=False)

4

In [18]:
query = "SELECT * FROM customers"

df = pd.read_sql(query, conn)
df.head()

   Customer_ID  Loan_Amount  Credit_Score
0            1       200000           720
1            2       150000           680
2            3       300000           650
3            4       180000           700